"""Reproducible, fully offline backtest using the Python API.

Runs the SMA crossover strategy on the bundled SYNTHETIC price series
(examples/data/synthetic.csv, generated by scripts/make_synthetic_data.py).
The output is deterministic, but it is a toy: the data is random, not market
data, so the numbers say nothing about real performance.

    python examples/offline_backtest.py
"""

from __future__ import annotations

from pathlib import Path

from sma_crossover import SmaCrossoverStrategy

from quantdeck.data.csv_feed import CSVDataFeed
from quantdeck.engine import BacktestEngine
from quantdeck.metrics import compute_metrics, compute_trade_pnls

DATA = Path(__file__).parent / "data" / "synthetic.csv"


def run() -> tuple[BacktestEngine, dict[str, float]]:
    engine = BacktestEngine(
        strategy=SmaCrossoverStrategy(),
        data_feed=CSVDataFeed(DATA),
        symbol="SYN",
        start="2022-01-01",
        end="2030-01-01",
        starting_cash=100_000.0,
        slippage_bps=5.0,
        commission=1.0,
    )
    curve = engine.run()
    m = compute_metrics([p.equity for p in curve], compute_trade_pnls(engine.fills))
    summary = {
        "bars": len(curve),
        "fills": len(engine.fills),
        "rejected": len(engine.rejected_orders),
        "total_return_pct": round(m.total_return_pct, 2),
        "sharpe": round(m.sharpe, 2),
        "max_drawdown_pct": round(m.max_drawdown_pct, 2),
        "ending_equity": round(curve[-1].equity, 2),
    }
    return engine, summary


if __name__ == "__main__":
    for key, value in run()[1].items():
        print(f"{key:>18}: {value}")
