"""Generate manual/api.md from the real signatures and docstrings.

python scripts/gen_api_docs.py            # rewrite manual/api.md
python scripts/gen_api_docs.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import enum
import importlib
import inspect
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "manual" / "api.md"

# (module, public names) in reading order.
API: list[tuple[str, list[str]]] = [
    ("quantdeck.strategy", ["Strategy"]),
    ("quantdeck.engine", ["BacktestEngine", "EquityPoint"]),
    ("quantdeck.models", ["Bar", "Order", "OrderSide", "Fill", "Position", "RejectedOrder"]),
    ("quantdeck.broker.base", ["Broker"]),
    ("quantdeck.broker.paper", ["PaperBroker"]),
    ("quantdeck.data.base", ["DataFeed"]),
    ("quantdeck.data.csv_feed", ["CSVDataFeed"]),
    ("quantdeck.data.yfinance_feed", ["YFinanceFeed"]),
    ("quantdeck.metrics", ["compute_metrics", "compute_trade_pnls", "Metrics"]),
    ("quantdeck.storage", ["Storage"]),
]


def _doc(obj: object) -> str:
    if inspect.isclass(obj):
        # Own docstring only: inherited ones (e.g. from Enum/str) differ by Python version.
        return inspect.cleandoc(obj.__dict__.get("__doc__") or "")
    return inspect.cleandoc(inspect.getdoc(obj) or "")


def _sig(name: str, obj: object) -> str:
    try:
        return f"{name}{inspect.signature(obj, eval_str=True)}"  # type: ignore[arg-type]
    except NameError:  # annotation only imported under TYPE_CHECKING
        return f"{name}{inspect.signature(obj)}".replace("'", "")  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return name


def render() -> str:
    out = [
        "# QuantDeck API reference",
        "",
        "Generated by `scripts/gen_api_docs.py` from the code's real signatures and "
        "docstrings; do not edit by hand (a test fails if it is stale).",
        "",
    ]
    for module_name, names in API:
        module = importlib.import_module(module_name)
        out += [f"## `{module_name}`", ""]
        for name in names:
            obj = getattr(module, name)
            kind = "class" if inspect.isclass(obj) else "def"
            if inspect.isclass(obj) and issubclass(obj, enum.Enum):
                # Enum signatures vary across Python versions; list the members instead.
                members = ", ".join(f"{m.name}={m.value!r}" for m in obj)
                out += [f"### `enum {name}`", "", f"Members: {members}", ""]
                continue
            out += [f"### `{kind} {_sig(name, obj)}`", ""]
            if _doc(obj) and not (inspect.isclass(obj) and _doc(obj).startswith(f"{name}(")):
                out += [_doc(obj), ""]
            if inspect.isclass(obj):
                for mname, member in vars(obj).items():
                    if mname.startswith("_"):
                        continue
                    target = member.fget if isinstance(member, property) else member
                    if not callable(target):
                        continue
                    label = "property" if isinstance(member, property) else "method"
                    sig = _sig(mname, target) if label == "method" else mname
                    out += [f"- **{label}** `{sig}`"]
                    if _doc(target):
                        first = _doc(target).split("\n\n")[0].replace("\n", " ")
                        out += [f"  - {first}"]
                out += [""]
    return "\n".join(out).rstrip() + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
